### ISSUE TITLE
Verbose / CLI Commands

### ISSUE THREAD

**Issue by docgonzo2015** [kmcclive/tricycle#112]
It looks easy peasy, but can you issue the CLI commands as verbose or debug mode? 
There are a few more options in Video Codec that belong as a base.
Is it possible to translate it or u have the textes scattereted inside code?

**Comment by kmcclive** [comment]
@docgonzo2015 I could use some clarification on your questions.
1. What are you trying to accomplish with verbose/debug via the CLI?  Tricycle doesn't have a CLI yet.  I opened issue #68 for that.
2. Which video codec options are you looking for that are missing?
3. I think it is possible to translate.  Which language do you want it translated to?  Are you able to provide the translations?

**Comment by docgonzo2015** [comment]
I have expressed myself incorrectly.
1. I would just like to see what comes out as a command in the end. This does not have to be shown in the CLI. A simple > output.txt is already enough.
2. the standard stuff for different film sources. For example 2018 action movies need different settings than a Belmondo movie from the 70s. There is virtually a basic preset that is customized with a few options. Fog is very helpful to set intra high. Comics it goes high with b-frames. Its examples, you understand what i mean?
3. I can deliver. German, France, Turkish, Polish and Russian I can deliver personally.  One language besides English is enough for me personally.


But the principle of tricycle should remain! Simple, few buttons to klick. The "special" options are linked to a button. Nobody is interested in the exactly settings.

**Comment by kmcclive** [comment]
I'm going to attempt to address each item individually.
1. You can view the command used by enabling trace logging in preferences/options (and restarting the app).  The logs will be located in ~/Library/Logs/Tricycle for macOS and %APPDATA%\Tricycle\Logs for Windows.
2. I'm not real clear on the options you're talking about, but I'm not sure they belong in Tricycle, to be honest.  Tricycle is intended to be real easy to pick up and use for those unfamiliar with video encoding, even at the expense of all the "bells and whistles". Some advanced options are configurable via preferences/options but those would apply to every video transcoded.  If you give me some more explicit examples on what FFmpeg arguments you want set and when, I might be able to come up with something, but I can't make any promises.
3. Wow!  That would be really helpful!  I think it would be nice to have a separate issue for each translation and the translations themselves attached to those.  Would you mind creating those or would you like me to?  To be clear, I don't have a timeline for when I'll be able to get those translations added.  I am the sole developer of this project right now.  I would also understand if you decide not to provide the translations if you find that Tricycle doesn't meet your needs.

**Comment by docgonzo2015** [comment]
That's exactly why I like tricycle. It is beautifully simple, like for toddlers. Or my parents. They have no idea about computers but want to convert a movie. That's how it should be designed.
Examples button: 

- Grainy Movie: deblock -1:-1, nr-intra 400, nr-inter 400
- Cartoon Movie: ref 6, bframes 16, aq-strenghgt 0.6
- Documentation : qcomp=0.7, frame-threads 2, merange 48
- Concert : copy audio

**Comment by kmcclive** [comment]
Thanks for the additional information.  That helps.  I will need to look up some of these options to get a better understanding of what they do.  I think being able to configure and select content presets would meet this need.  I considered adding something like that to be able to leverage VideoToolbox on macOS, which does not support CRF.  In that case, I was considering fine tuning bitrates for different content types.

FYI, Tricycle may have some features to already support a couple of the scenarios you mentioned.  For grainy movies, you can already enable noise reduction.  For concerts, if by "copy audio", you mean passthrough instead of transcode, that is already done automatically if the audio format and "mixdown" (mono/stereo/surround) matches the source.

**Comment by kmcclive** [comment]
@docgonzo2015 I created a couple issues to replace this one: #117 to support the additional codec options and #118 for a first translation.  I chose French because I am most familiar with it and it appears to be the most spoken in the world out of the list you provided.
