### ISSUE TITLE
Feature Request: Output ffmpeg command string for Linux users

### ISSUE THREAD

**Issue by inthebrilliantblue** [kmcclive/tricycle#128]
Been using tricycle for a while, and it has really been useful in handling HDR content. However, I have several linux boxes that I want to use with tricycle, but tricycle doesnt have linux support yet. Is it possible to generate a command string that I can copy/pasta to my linux boxes while waiting for Linux support? This would also help me to avoid long running conversions from being interrupted by Windows updates rebooting in the middle of the night.

**Comment by kmcclive** [comment]
@inthebrilliantblue Tricycle already logs all of its commands if you configure it to do so.  Please keep in mind that you may need to reformat them depending on the shell you're using.  You can use these steps to enable logging and access the log file.

1. Go to Tools > Options
2. Select Advanced from the left navigation
3. Check the Trace Logging box
4. Restart the app
5. Start a transcode
6. Locate the log file in %localappdata%/Tricycle/Logs (you can type that in the Windows search box)

FYI, I wouldn't recommend keeping logging enabled all the time.  It writes _a lot_ of messages to the file.  Does this satisfy your request?

**Comment by inthebrilliantblue** [comment]
Absolutely, thanks! I didnt know it did that.
