### ISSUE TITLE
What do the gray line represent

### ISSUE THREAD

**Issue by marco-luo928420** [kmcclive/tricycle#146]
hi,when i use function "plot_ccposition_den" to plot,there is a gray line in the plot,So,i want to ask what do the gray line mean,could i remove the gray line in the plot? thanks a lot

**Comment by kmcclive** [comment]
Hi, @marco-luo928420.  I think you added this issue to the wrong repository.  I think you will find the correct one [here](https://github.com/hansenlab/tricycle).

**Comment by marco-luo928420** [comment]
sorry,I didn't express clearly.I want to know what the gray line represent for in this plot?Thanks a lot
![e011e703d911bb2e82e157d6d5b8559](https://github.com/kmcclive/tricycle/assets/109411092/8ca404a0-1f95-4bdf-a02c-13feeee5038a)
