### ISSUE TITLE
Just stumbled upon this app and it refuses to work, also have a feat request :D

### ISSUE THREAD

**Issue by morpheus2n2** [kmcclive/tricycle#84]
No matter what I do it will always tell me "Not such directory exists" so I can not convert any single file at the mo :(

Also is it possible to add an option to choose your own bitrate for a video?

**Comment by morpheus2n2** [comment]
I have found that I get this error if.

1.  I set Dolby Digital
2. If I choose Subtitles

So basically If I change any settings other then default I get a error telling me "No Such directory"

**Comment by kmcclive** [comment]
@morpheus2n2 Are you using the macOS or Windows app?  At what point do you get the error "No such directory exists"?  Is it when you start a transcode or when you make a selection?  It would be helpful if you sent me a log file.  I will send you specific instructions for doing that once I know which OS you are using.

To answer your other question about bitrates, Tricycle doesn't specify bitrates; it uses CRF.  The CRF values can be modified on the Options/Preferences page.  Issue #67 is a request to limit the bitrate.  Do either of these meet your needs?

**Comment by morpheus2n2** [comment]
Windows, I found that you get it as soon as you hit start if you changed either the Audio or choose a subtitle file.
If I leave it all default the app will work fine

**Comment by kmcclive** [comment]
@morpheus2n2 Would you please enable logging and send me a log file?  Here are the steps:
1. Start the app
1. Go to Tools > Options
1. Select Advanced from the left navigation
1. Check the Trace Logging box
1. Restart the app
1. Recreate the problem
1. Close the app
1. Locate the log file in %localappdata%/Tricycle/Logs (you can type that in the Windows search box)
1. Attach the file to this issue (drag it to the comment box)
