### ISSUE TITLE
Converted Video Unplayable on Mac

### ISSUE THREAD

**Issue by noonetooimportant123** [kmcclive/tricycle#94]
I've tried converting a few MKV video files (4k, HDR) to h.265/HVEC mp4. The resulting m4v files won't open on a Mac. I'm not sure if this is an issue or if I'm missing something.

**Comment by kmcclive** [comment]
@noonetooimportant123 What app did use to try to play them?  All the videos that I've converted play just fine with VLC.  I just tried one of them with both QuickTime Player and the TV app.  QuickTime Player gave an error whereas the TV app played the sound but no video.

**Comment by noonetooimportant123** [comment]
I was trying Quicktime. VLC does play them, but I was hoping to be able to transfer them to an iPad/iPhone and play them natively.

**Comment by kmcclive** [comment]
@noonetooimportant123 I will have to look into that.  I'm not sure if I'll be able to make them playable for QuickTime, but I have a theory about why the video isn't showing up in the TV app.  Fixing that may make it playable from the TV app on iPads and iPhones.
